channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - codecov
  - pytest
  - landlab
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - geopandas
  - xarray
  - dask
  - cartopy
  - conda-build
  - pytest-cov
  - rasterio
  - pygeos=0.10.2
  - contextily