channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - codecov
  - pytest
  - landlab
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - geopandas>=0.12
  - xarray
  - dask
  - cartopy
  - conda-build
  - pytest-cov
  - rasterio
  - pygeos
  - contextily
  - hypothesis
  - cftime